### ISSUE TITLE
🪲 Bug Report - Recent update removed tags column from generated spreadsheet

### ISSUE THREAD

**Issue by humblejay** [Azure/Azure-Proactive-Resiliency-Library-v2#121]
## Describe the bug

Recent changes to  tools/2_wara_data_analyzer.ps1  is not adding the tags column to the generated Excel.  This column is useful in filtering out-of-scope resources.

## To Reproduce

Steps to reproduce the behaviour:

Run script

## Expected behaviour

Generated spreadsheet needs to have "tags" column similar to the earlier version of this script.

## Screenshots 📷

If applicable, add screenshots to help explain your problem. Please feel free to blur/cover any sensitive information.

## Additional context

Anything else we should know to help us troubleshoot this bug?

**Comment by ejhenry** [comment]
Thanks for opening this issue @humblejay. The removal of tags from the Excel spreadsheet was an intentional change to address privacy concerns related to the type of data some customers put in their tags. 

If you would like to see additional functionality around filtering out-of-scope resources, please open a feature request that describes the solution you'd like to see.
