### ISSUE TITLE
💡 Feature Request - DocumentDB/databaseAccounts CosmoDB recommendations

### ISSUE THREAD

**Issue by FallenHoot** [Azure/Azure-Proactive-Resiliency-Library-v2#247]
## Describe the solution you'd like

If Cosmo DB NoSQL is using Multi-Region Writes, then it is recommended by Microsoft to not enable Availability Zone support as it provides limited value. As documented in the [learn docs](https://learn.microsoft.com/en-us/azure/reliability/reliability-cosmos-db-nosql#impact-of-using-availability-zones:~:text=In%20many%20cases%2C%20availability%20zones%20don%E2%80%99t%20add%20value%20or%20add%20minimal%20value%20if%20the%20account%20is%20multi%2Dregion%20(unless%20configured%20with%20strong%20consistency).). Following the guidance shared in - the learn docs around the [impact of using availability zones with Multi-Region Writes enabled](https://learn.microsoft.com/en-us/azure/reliability/reliability-cosmos-db-nosql#impact-of-using-availability-zones:~:text=No%20availability%20loss-,No%20availability%20loss,No%20availability%20loss,-Regional%20outage%3A%20data). AZs for Multi-Region writes are free, and it is assumed having them turned on doesn't affect the reliability of Cosmo DB when using Multi-Region Writes. 

It should be noted that having AZ enabled only is recommended if strong consistency is being used. Multi-Region Writes do [not support strong consistency](https://learn.microsoft.com/en-us/azure/cosmos-db/consistency-levels#strong-consistency-and-multiple-write-regions). 

> Cosmos DB accounts configured with multiple write regions can't be configured for strong consistency as it isn't possible for a distributed system to provide an RPO of zero and an RTO of zero. 

I have also updated the wording in the learn docs to reflect this - https://github.com/MicrosoftDocs/azure-docs/pull/123628

**Recommendation:**
The feature request is two folds: If Multi-Region writes is enabled, then AZs are grayed out, as they provide limited value.

## Describe alternatives you've considered

No alternatives

## Additional context

All context is added to the above.

**Comment by kovarikthomas** [comment]
Hi Zach (@FallenHoot) and Eric (@ejhenry) - while I do not know where you would like to "gray out" the AZ option (Portal, docs, someplace else?), I would prefer we **do not** do it anywhere. 

 _"it is recommended by Microsoft to not enable Availability Zone support as it provides limited value"_

Rather than recommending against AZs, the referenced docs point at diminishing returns from enabling AZs if other resiliency features/options are also used - e.g., multiple read regions, or multi-region writes. In all cases, AZs are beneficial, and as you mentioned, with multi-region writes, they come for free. As long as the given Azure region supports AZs and there's sufficient capacity, customers should absolutely enable them. 

To be specific, for multi-region writes configured accounts AZs are still beneficial when outage occurs on: 

- conflict-resolution region, which is exactly one of configured regions - in such a case, temporary loss of write availability occurs until new conflict resolution region is elected (refer: [docs](https://learn.microsoft.com/en-us/azure/reliability/reliability-cosmos-db-nosql#read-and-write-outages)). With AZs enabled all four replicas are spread across all available zones which ensures that in the event of an outage in one AZ, the account remains fully operational and conflict resolution region election is not required. In contrast, without AZs, all replicas would be located in a single AZ (we do not expose which), leading to potential downtime if that specific zone experienced an issue.
- any non-conflict resolution region - assuming AZs are not used and that particular AZ hosting all replicas experiences an outage, account will seamlessly and instantaneously retry operations on other regions (as defined in Preferred Regions list, refer [docs]( https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-multi-master?tabs=api-async#java4-multi-region-writes)). While this limits/eliminates any downtime, CRUD operations now experience higher latency due to calls being made across Azure regions. With AZs enabled, Cosmos DB would dynamically downshift quorum and calls would continue to be served with low latency from the unaffected AZs in the original region.

**Comment by ejhenry** [comment]
Thanks @kovarikthomas. @FallenHoot any concerns with closing this issue?
