### ISSUE TITLE
🪲 Bug Report - Recommendation "Deploy VMs across Availability Zones" provides false positive for resources in Azure region where AZ is not supported.

### ISSUE THREAD

**Issue by maheshbenke** [Azure/Azure-Proactive-Resiliency-Library-v2#351]
## Describe the bug

ARG query for Recommendation "Deploy VMs across Availability Zones" returns VM's which are present in Azure regions where AZ is not supported, resulting in a false positive.

## To Reproduce

Steps to reproduce the behaviour:

1. Run the Below ARG query against any subscription which as resources in Azure regions where AZ is not supported (example: WestUS)

## Expected behaviour

The ARG query results should exclude results from regions where AZ is not supported or available.

## Screenshots 📷

NA

## Additional context

NA

**Comment by ejhenry** [comment]
Thanks for opening this @maheshbenke. The current approach of identifying VMs as non-compliant in regions that do not have AZs is intentional. Ultimately, region selection is a design decision that has downstream implications for the workload. Considering evaluation of zonal redundancy is mandatory for reliability assessments, it makes sense to highlight non-compliant resources regardless of the region where they are deployed. Let's discuss further if you disagree.

**Comment by ejhenry** [comment]
@maheshbenke the ARG query now validates the region where the resources are deployed supports AZs.
