### ISSUE TITLE
❓👂 Question/Feedback - PVDNSZ-1 - Protect private DNS zones and records

### ISSUE THREAD

**Issue by ReneHezser** [Azure/Azure-Proactive-Resiliency-Library-v2#45]
## Question/Feedback

1. What is the purpose of recommendation PVDNSZ-1. *Protect private DNS zones and records*
  The private DNS Zone to have this role assigned?
2. can we clarify the guidance for PVDNSZ-2. *Monitor Private DNS Zones health and set up alerts*
  What needs to be checked for it to be green?
3. can we clarify the guidance for PVDNSZ-3. *Align Production and DR zones with identical workload and resource failover entries*
  Are custom domains relevant for reliability? This is what I understand from this recommendation. Private DNS Zones without a custom domain will be flagged by this?

For the recommendations it is unclear what needs to be checked for them to pass. What is the criteria for them to mark them as fullfilled?

**Comment by ejhenry** [comment]
cc @JefferyMitchell

**Comment by JefferyMitchell** [comment]
@Azure/aprl-networking Could you review and share your thoughts on this feedback.

**Comment by JefferyMitchell** [comment]
@ReneHezser The team is looking into and discussing updates currently.

**Comment by ehaslett** [comment]
This is being tracked via https://dev.azure.com/CSUSolEng/Azure%20Infra%20Networking/_workitems/edit/35189/

To follow-up on Jeff's previous questions:

> @ReneHezser The team is looking into and discussing updates currently. We agree there needs to be more clarity. Could you provide and feedback on what clarity you are looking for? Would be very helpful sharing your perception of the wording 🙏 so we can remove any ambiguity.

**Comment by ehaslett** [comment]
@ReneHezser - feel free to re-assign after following up on the question above around clarity. Many thanks!

**Comment by ReneHezser** [comment]
@ehaslett I've updated the initial post to clarify the ask.

**Comment by ehaslett** [comment]
Scheduled for completion August 2024

**Comment by ehaslett** [comment]
@ReneHezser, please see my comments below and respond if you can:

What is the purpose of recommendation PVDNSZ-1. Protect private DNS zones and records
Q: The private DNS Zone to have this role assigned?
A: Any/all private DNZ zones. Would you recommend stating this explciitly?

can we clarify the guidance for PVDNSZ-2. Monitor Private DNS Zones health and set up alerts
Q: What needs to be checked for it to be green?
A: The wording on this section is incorrect and will be updated. To answer your question, monitoring and alerting should be configured. I am not sure what is meant by "it to be green" though. Do you mean an ARG query?


can we clarify the guidance for PVDNSZ-3. Align Production and DR zones with identical workload and resource failover entries
Q: Are custom domains relevant for reliability? This is what I understand from this recommendation. Private DNS Zones without a custom domain will be flagged by this?
A: This recommendation is more specific to a situation where there exists a primary and DR region, each with it's own linked private DNS zones. The recommendation is to create the same DNS entries for each region so that at the application level there is no configuration change to DNS entries configured in the application. In this context, custom domains are relevant. That a private DNS zone is not custom would not cause it to be flagged. For example, any zone supporting a private endpoint for Private Link.
